name: Test Schedule

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Testar agendamento
        run: echo "SCHEDULE FUNCIONANDO"
